TopPageを実装しました。
shinonome-inc/mobile_Aoi_mogi_Qiita pull request #1
Opened 2021-08-27 17:08 UTC by aoinishinaka

ToPageを実装しました。今度こそ差分を表示できているはずです。

2021-08-29 01:12 UTC, mcz9mm requested changes
コメントしました

2021-08-29 01:12 UTC, mcz9mm commented on lib/main.dart
> +        '/Bottom':(context)=>BottomNavigation(),
`:` コロンの後は半角スペース、`=>`の前後に半角スペース
`'/Bottom': (context) => BottomNavigation(),`

2021-08-29 01:12 UTC, mcz9mm commented on lib/main.dart
> +Color bottomGray=Color(0xFF828282);
どのクラス・ファイルから参照できるトップレベル変数、グローバル変数なので
`constants.dart`などのファイルを作ってそこに書いてください。

2021-08-29 01:12 UTC, mcz9mm commented on lib/main.dart
> +Color bottomGray=Color(0xFF828282);
`=`の前後は半角スペース
`Color bottomGray = Color(0xFF828282);`

2021-08-29 01:12 UTC, mcz9mm commented on lib/main.dart
> +Color bottomGray=Color(0xFF828282);
final、constを使っておくと良いです。

final Color bottomGray = const Color(0xFF828282);

意識して設定するようにしてください。
http://jpsepower.sakura.ne.jp/wp/dart%E3%81%AE%E5%A4%89%E6%95%B0%E5%AE%A3%E8%A8%80%EF%BC%88var-final-const%EF%BC%89%E3%81%AE%E9%81%95%E3%81%84/

2021-08-29 01:12 UTC, mcz9mm commented on lib/top_page.dart
> +class Top extends StatefulWidget {
`StatefulWidget `にしている理由がなければ`StatelessWidget`で

2021-08-29 01:12 UTC, mcz9mm commented on lib/top_page.dart
> +            Expanded(flex:22,child:Container()),
`:`コロンの後は半角スペース、改行以外の`,`カンマの後は半角スペース
`Expanded(flex: 22, child: Container()),`

2021-08-29 01:12 UTC, mcz9mm commented on lib/top_page.dart
> +            Expanded(flex:22,child:Container()),
22にした理由を教えてください〜
22:33:3:8の比率でExpandedが設定された経緯とかあれば

2021-08-29 01:12 UTC, mcz9mm commented on lib/top_page.dart
> +              width: 344,
どの画面サイズ、デバイスであっても横幅が固定サイズになってるので画面サイズによって可変になるようにしてください

2021-08-29 12:37 UTC, aoinishinaka commented on lib/top_page.dart
> +            Expanded(flex:22,child:Container()),
figmaで長さを測りその比から算出しました。しかし その比が正確でなくExpandedを用いる余白が４か所ではなく５か所あったため修正しました。

2021-08-29 12:37 UTC, aoinishinaka commented on lib/top_page.dart
> +class Top extends StatefulWidget {
修正しました

2021-08-29 12:38 UTC, aoinishinaka commented on lib/main.dart
> +Color bottomGray=Color(0xFF828282);
修正しました

2021-08-29 12:38 UTC, aoinishinaka commented on lib/top_page.dart
> +              width: 344,
修正しました

2021-09-04 02:40 UTC, mcz9mm requested changes
全部をFlexの比率にするのではなく固定値の部分もあるので修正してみましょう。
青枠の部分がExpandedすると良いと思います
<img width="372" alt="スクリーンショット 2021-09-04 11 39 17" src="https://user-images.githubusercontent.com/11751495/132079774-216bc96b-789d-4360-80cd-afdcef4b9a88.png">

2021-09-04 02:40 UTC, mcz9mm commented on lib/top_page.dart
> +              'prey ground',
タイポしてる😭`-PlayGround-`

2021-09-04 02:40 UTC, mcz9mm commented on lib/top_page.dart
> +              width: MediaQuery.of(context).size.width *0.872,
Figmaで左右の余白を確認してください。
パーツを横幅に広がるようにし、Paddingで余白をつけてあげればこのように0.872というような値を設定する必要はありません。
<img width="532" alt="スクリーンショット 2021-09-04 11 28 20" src="https://user-images.githubusercontent.com/11751495/132079487-2cb5175e-b7c2-410c-ba72-33804fbef582.png">

2021-09-04 02:40 UTC, mcz9mm commented on lib/top_page.dart
> +            Expanded(flex: 34, child: Container()),
ボタン間の余白は16pt
比率ではなく固定値
<img width="534" alt="スクリーンショット 2021-09-04 11 31 02" src="https://user-images.githubusercontent.com/11751495/132079571-0e361a20-8054-4788-be1a-8fc17bc4303a.png">

2021-09-04 02:40 UTC, mcz9mm commented on lib/top_page.dart
> +              'Qiita feed App',
`Qiita Feed App`

2021-09-04 02:40 UTC, mcz9mm commented on lib/top_page.dart
> +            Expanded(flex: 8, child: Container()),
ここの余白は8pt

2021-09-05 12:17 UTC, aoinishinaka commented on lib/top_page.dart
> +              width: MediaQuery.of(context).size.width *0.872,
修正しました。

2021-09-05 12:17 UTC, aoinishinaka commented on lib/top_page.dart
> +              'prey ground',
修正しました…すみません。

2021-09-05 12:17 UTC, aoinishinaka commented on lib/top_page.dart
> +            Expanded(flex: 34, child: Container()),
修正しました。

2021-09-05 12:17 UTC, aoinishinaka commented on lib/top_page.dart
> +            Expanded(flex: 8, child: Container()),
修正しました

2021-09-16 05:08 UTC, mcz9mm commented on lib/top_page.dart
> +            Expanded(flex: 220, child: SizedBox()),
Expandedでスペースを作るときは中身Containerのままで良いです。
SizedBoxは固定値でサイズを確保するときに使います。

2021-09-16 05:08 UTC, mcz9mm commented on lib/top_page.dart
> +            Expanded(flex: 64, child: SizedBox()),
Expandedでスペースを作るときは中身Containerのままで良いです。
SizedBoxは固定値でサイズを確保するときに使います。

2021-09-16 05:08 UTC, mcz9mm commented on lib/top_page.dart
> +            Expanded(flex: 321, child: SizedBox()),
Expandedでスペースを作るときは中身Containerのままで良いです。
SizedBoxは固定値でサイズを確保するときに使います。

2021-09-16 13:49 UTC, aoinishinaka commented on lib/top_page.dart
> +            Expanded(flex: 321, child: SizedBox()),
修正しました。

2021-09-16 13:49 UTC, aoinishinaka commented on lib/top_page.dart
> +            Expanded(flex: 64, child: SizedBox()),
修正しました。

2021-09-16 13:50 UTC, aoinishinaka commented on lib/top_page.dart
> +            Expanded(flex: 220, child: SizedBox()),
修正しました。

2021-09-16 13:58 UTC, merged