FeedPageを作成しました。
shinonome-inc/mobile_Aoi_mogi_Qiita pull request #2
Opened 2021-09-27 05:05 UTC by aoinishinaka

FeedPageのApiからのデータ取得を実装しました。SearchBarと記事を押すとArticlePageに移動する機能は難しそうなので、他のページから作成したいと思います。

2021-09-27 10:00 UTC, mcz9mm requested changes
プロジェクト内にqiitappというのがさらにプロジェクトが作成されてしまっているので削除してください。不要な実装が含まれているので消してからレビューします。

2021-09-27 10:00 UTC, mcz9mm commented on lib/Api/model/qiita_api.dart
> +class User{
`User`クラスは他でも使うと思うので別ファイルを作成してそこで定義してください。
`user.dart`

2021-09-27 10:00 UTC, mcz9mm commented on lib/Api/model/qiita_api.dart
> +class QiitaApi{
`QiitaApi`の中身って記事のデータだよね。
このクラス自体がデータ通信を行えるクラス名にしか見えないので、
APIの言葉と意味合いが違うので別のクラス名にしてあげてください。
記事だとArticleとか
> API とは、アプリケーションやソフトウェアの構築と統合 (インテグレーション) に使われるツール、定義、プロトコルです。 API は、Application Programming Interface (アプリケーション・プログラミング・インタフェース) の略です。

2021-09-27 10:00 UTC, mcz9mm commented on lib/Api/network_request.dart
> +class Qiita{
細かいけど　`{`の前に半角スペース
`class Qiita {`

2021-09-27 10:00 UTC, mcz9mm commented on lib/bottomnavigation.dart
> +                child: MaterialApp(home:FeedPage()),
MaterialAppでラップしている理由は？
必要ないと思うけど

2021-09-27 10:00 UTC, mcz9mm commented on lib/bottomnavigation.dart
> +              offstage: index !=0,
`=`などの条件式の間には半角スペースにしてください。
下の部分も全部一緒
`index != 0,`

2021-09-27 10:00 UTC, mcz9mm commented on lib/feed_page.dart
> +                    decoration:  BoxDecoration(color: Colors.amber, borderRadius: new BorderRadius.only(topLeft: const Radius.circular(20.0), topRight: const Radius.circular(20.0))),
この辺のコードのインデントが崩れているせいで可読性が悪いです。
Android Studioの設定でコード整形してくれるものがあるので導入して修正してください。
https://nobushiueshi.com/flutterandroid-studio%E3%81%A8visual-studio-code%E3%81%A7%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%89%E6%95%B4%E5%BD%A2%E3%81%AE%E4%BB%95%E6%96%B9/

2021-09-27 10:00 UTC, mcz9mm commented on lib/feed_page.dart
> +                    decoration:  BoxDecoration(color: Colors.amber, borderRadius: new BorderRadius.only(topLeft: const Radius.circular(20.0), topRight: const Radius.circular(20.0))),
あと、今のFlutterのバージョンで`new`は不要です。
古いコードを記載している記事などではnewがついたままになっているので
注意してください、

2021-09-27 10:00 UTC, mcz9mm commented on lib/feed_page.dart
> +                    child: WebView(
`webview_flutter`使ってるよね。
pubspec.yamlにパッケージ追加したと思うんだけどそれもgit add してもらわないとこっちでビルドできないので更新お願いします。

https://pub.dev/packages/webview_flutter/install

2021-09-27 10:05 UTC, mcz9mm commented
作成したPRはベースとなるブランチとの差分が表示されます。
プロジェクト作成時などは生成されるファイルの関係でコードやファイル数が多くなるのはわかりますが、
機能追加の実装でここまでのファイル数の変更やコード量の差分はほとんどありえないので、
何かしら間違っている可能性があると思ってください。

<img width="429" alt="スクリーンショット 2021-09-27 19 04 06" src="https://user-images.githubusercontent.com/11751495/134888415-ad65bc63-2399-4f92-a1fd-0fceae52dc79.png">

2021-09-27 14:02 UTC, aoinishinaka commented on lib/bottomnavigation.dart
> +              offstage: index !=0,
修正しました。

2021-09-27 14:03 UTC, aoinishinaka commented on lib/feed_page.dart
> +                    decoration:  BoxDecoration(color: Colors.amber, borderRadius: new BorderRadius.only(topLeft: const Radius.circular(20.0), topRight: const Radius.circular(20.0))),
了解です！

2021-09-27 14:04 UTC, aoinishinaka commented on lib/bottomnavigation.dart
> +                child: MaterialApp(home:FeedPage()),
参考にしたコードが使っていたので入れました。すみません

2021-09-27 14:04 UTC, aoinishinaka commented on lib/Api/network_request.dart
> +class Qiita{
修正しました。

2021-09-27 14:04 UTC, aoinishinaka commented on lib/Api/model/qiita_api.dart
> +class QiitaApi{
修正しました。

2021-09-27 14:04 UTC, aoinishinaka commented on lib/Api/model/qiita_api.dart
> +class User{
修正しました

2021-09-28 01:52 UTC, mcz9mm requested changes
サイズの違う端末でもチェックして問題ないか確認した後にレビュー出すようにしてください

2021-09-28 01:52 UTC, mcz9mm commented on lib/Api/model/qiita_api.dart
> +class Article{
ファイル名も対応させてあげよう

`qiita_api.dart`→`article.dart`

2021-09-28 01:52 UTC, mcz9mm commented on lib/Api/model/user.dart
> +  User({required this.id, required this.profile_image_url});
👍

2021-09-28 01:52 UTC, mcz9mm commented on lib/bottomnavigation.dart
> +            Offstage(
Offstageは必要ないかな〜
こちらの公式ドキュメントのサンプル実装を元に作成してください

https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html

2021-09-28 01:52 UTC, mcz9mm commented on lib/feed_page.dart
> +                                    Row(
Figmaのデザインと要件通りに実装してください。
投稿日の日付のフォーマットを合わせる
区切り線の位置はタイトルやサブタイトルの位置に合わせるなど
<img width="500" alt="スクリーンショット 2021-09-28 10 39 42" src="https://user-images.githubusercontent.com/11751495/135008240-de8049b6-bb40-4dbb-8f68-bf51592ff34b.png">

<img width="500" alt="スクリーンショット 2021-09-28 10 38 38" src="https://user-images.githubusercontent.com/11751495/135008176-e91c2fbb-7c4a-4592-ab20-1ba6d39433d0.png">

2021-09-28 01:52 UTC, mcz9mm commented on lib/bottomnavigation.dart
> +        bottomNavigationBar: SizedBox(
BottomNavigationBarにサイズ指定するとデバイスによっては高さが収まらないのでSizedBoxは不要です。
<img width="648" alt="スクリーンショット 2021-09-28 10 43 25" src="https://user-images.githubusercontent.com/11751495/135008535-63ad6a50-a03a-490d-a3a1-08c645f52d43.png">

2021-09-28 01:52 UTC, mcz9mm commented on lib/feed_page.dart
> +                                height: 500,
ここの500の理由はなんだろう
デバイスの高さに合わせた方がUIが良くなるんじゃないかな。

2021-09-28 01:52 UTC, mcz9mm commented on lib/feed_page.dart
> +                          showModalBottomSheet<void>(
onTapの中身の処理が長くなるので、メソッドを定義して呼び出せるようにしてあげてください。
必要な情報は引数で渡す
```
  void showArticlePage(String url) {
    showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(15)),
      ),
      builder: (BuildContext context) {
        return Container(
          height: 500,
          child: Column(
            children: [
              Container(
                child: Text(
                  'Article',
                  style: TextStyle(fontSize: 17, fontFamily: 'Pacifico'),
                ),
              ),
              Container(
                decoration: BoxDecoration(
                    color: Colors.amber,
                    borderRadius: BorderRadius.only(
                        topLeft: const Radius.circular(20.0),
                        topRight: const Radius.circular(20.0))),
                child: Container(
                    child: WebView(
                  initialUrl: url,
                )),
              ),
            ],
          ),
        );
      },
    );
  }
```

タップ時の実装が見やすくなります。
```
                      InkWell(
                        onTap: () {
                          showArticlePage(article.url);
                        },
```

2021-09-28 01:52 UTC, mcz9mm commented on lib/feed_page.dart
> +                                height: 500,
pixel4aだと表示崩れが起きてます。
<img width="300" alt="スクリーンショット 2021-09-28 10 47 22" src="https://user-images.githubusercontent.com/11751495/135009154-25d4dcd0-5f99-457b-b0de-664cf13a9d0a.png">

2021-09-29 15:40 UTC, aoinishinaka commented on lib/bottomnavigation.dart
> +        bottomNavigationBar: SizedBox(
修正しました。

2021-09-29 15:40 UTC, aoinishinaka commented on lib/feed_page.dart
> +                                    Row(
修正しました。

2021-09-29 15:40 UTC, aoinishinaka commented on lib/bottomnavigation.dart
> +            Offstage(
修正しました。

2021-09-29 15:41 UTC, aoinishinaka commented on lib/feed_page.dart
> +                                height: 500,
修正しました。

2021-09-29 15:41 UTC, aoinishinaka commented on lib/feed_page.dart
> +                          showModalBottomSheet<void>(
修正しました・。

2021-09-29 15:43 UTC, aoinishinaka commented on lib/feed_page.dart
> +                                height: 500,
webviewを用いて記事を表示できるようになったのですが、表示した記事がスクロールできません。どのようなものを用いればよいでしょうか？

2021-09-29 17:24 UTC, mcz9mm commented on lib/feed_page.dart
> +    return Expanded(
ごめん早めに気づいてあげればよかったんだけど、なんでも広げるためにExpandedを使うと怒られるんだよね。
Expandedが使えるのはStackやColumnやRowなどの要素の中だけで、今回は`body: Center(`の要素になっているので警告が出てると思います。

```
        body: Center(
          child: FutureBuilder<List<Article>>(
              future: Qiita.fetchArticle(),
              builder: (BuildContext context,
                  AsyncSnapshot<List<Article>> snapshot) {
                if (snapshot.connectionState != ConnectionState.done) {
                  return CircularProgressIndicator();
                }

                if (snapshot.hasError) {
                  return Text(snapshot.error.toString());
                }

                if (snapshot.hasData) {
                  return QiitaCard(
                    qiitacard: snapshot.data!,
                  );
```

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Center widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  Stack ← RefreshIndicator ← Expanded ← QiitaCard ← FutureBuilder<List<Article>> ← Center ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5723:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5739:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5761:7)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5440:5)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6228:11)
...
====================================================================================================

```

2021-09-29 17:24 UTC, mcz9mm commented on lib/feed_page.dart
> +    return Expanded(
Expandedは不要なので外しておいてください。
<img width="1221" alt="スクリーンショット 2021-09-30 2 08 48" src="https://user-images.githubusercontent.com/11751495/135316404-bf4ca89c-57a8-4396-aec4-121ebdbe6805.png">

2021-09-29 17:24 UTC, mcz9mm commented on lib/feed_page.dart
> +                  DateTime dateTime = DateTime.parse(article.created_at);
これ定義したけど使ってないよ

2021-09-29 17:24 UTC, mcz9mm commented on lib/feed_page.dart
> +                  DateTime dateTime = DateTime.parse(article.created_at);
https://github.com/shinonome-inc/mobile_Aoi_mogi_Qiita/pull/2/files#diff-080109563d3144ece335bf94440ffb7fcee04e06049c433b8ef3b4d6c2bd5db2R162

2021-09-29 17:24 UTC, mcz9mm commented on lib/feed_page.dart
> +                      Divider(
区切り線はテキスト部分と同じ位置に来るようにしてください
Figmaのデザイン通りに作ってね〜
(案件や実際のエンジニアはこういったデザインデータを忠実に再現して実装するスキルが求められます)
<img width="733" alt="スクリーンショット 2021-09-30 2 19 48" src="https://user-images.githubusercontent.com/11751495/135317939-af663858-3cdc-495b-a9c4-23230e5b1fc9.png">

2021-09-29 17:24 UTC, mcz9mm commented on lib/feed_page.dart
> +                      Divider(
indentって引数を設定できます

2021-09-29 17:24 UTC, mcz9mm commented on lib/feed_page.dart
> +  Widget _model(Article article) {
不要な実装？使っていないなら消してください

2021-09-29 17:24 UTC, mcz9mm commented on lib/feed_page.dart
> +        appBar: PreferredSize(
ここは検索バーの実装の時にレビューします

2021-09-29 17:24 UTC, mcz9mm commented on pubspec.yaml
> +  flutter_riverpod: ^0.14.0+3
flutter_riverpod使うのはまだやめておいた方がいいかも
純粋にStatefulWidgetでできなくなったり、Providerを使ってみてから導入してください。
少なくとも最終課題ではProviderで十分だと思う。

2021-09-30 03:52 UTC, aoinishinaka commented on lib/feed_page.dart
> +                      Divider(
了解です！

2021-09-30 03:52 UTC, aoinishinaka commented on lib/feed_page.dart
> +  Widget _model(Article article) {
修正しました。

2021-09-30 03:52 UTC, aoinishinaka commented on lib/feed_page.dart
> +        appBar: PreferredSize(
了解です

2021-09-30 03:52 UTC, aoinishinaka commented on pubspec.yaml
> +  flutter_riverpod: ^0.14.0+3
修正しました。

2021-09-30 03:53 UTC, aoinishinaka commented on lib/feed_page.dart
> +                  DateTime dateTime = DateTime.parse(article.created_at);
修正しました。

2021-09-30 03:53 UTC, aoinishinaka commented on lib/feed_page.dart
> +    return Expanded(
修正しました。

2021-09-30 04:39 UTC, mcz9mm requested changes
コメントしました

2021-09-30 04:39 UTC, mcz9mm commented on lib/feed_page.dart
> +  Widget model(Article article) {
自分が言いたかったのは、このmodelっていう関数自体どこでも利用されてないから
消してほしいということです。

2021-09-30 04:39 UTC, mcz9mm commented on lib/feed_page.dart
> +  Widget model(Article article) {
<img width="440" alt="スクリーンショット 2021-09-30 13 37 45" src="https://user-images.githubusercontent.com/11751495/135388206-8e52dc2a-5de8-48ed-b583-8f56d882560b.png">

```
Widget model(Article article) {
    return Container(
      height: MediaQuery.of(context).size.height * 0.8,
      child: Column(
        children: <Widget>[
          Container(
            height: 60,
            decoration: BoxDecoration(
              color: Colors.grey[300],
              borderRadius: const BorderRadius.only(
                topRight: const Radius.circular(20),
                topLeft: const Radius.circular(20),
              ),
            ),
            child: Align(
              alignment: Alignment.center,
              child: Text(
                "Article",
                style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                  fontSize: 20,
                  fontFamily: 'Pacifico',
                ),
              ),
            ),
          ),
          Container(
            color: Colors.white,
            child: Padding(
                padding: const EdgeInsets.all(10.0),
                child: WebView(
                  initialUrl: article.url,
                )),
          ),
        ],
      ),
    );
  }
```

2021-09-30 04:54 UTC, aoinishinaka commented on lib/feed_page.dart
> +  Widget model(Article article) {
すいません！修正しました

2021-09-30 05:15 UTC, mcz9mm commented
ひとまずOKだと思います。
細かい箇所で微修正があると思いますがそれは追々直していきましょう。

2021-09-30 05:15 UTC, merged