showBottomSheetの移動＆SettingsPageの作成
shinonome-inc/mobile_Aoi_mogi_Qiita pull request #3
Opened 2021-10-04 15:14 UTC by aoinishinaka

ログアウト機能以外のSettingsPageを実装しました。

2021-10-04 23:55 UTC, mcz9mm commented
commitってそのcommit単位で遡ったり確認できたりするんだよね。その時点でのセーブデータみたいなものをイメージするとわかると思うけど、設定ページの実装をするのにいくつか作業をこまめに分割した方がわかりやすいかな。
`不要な関数の削除`というコミットメッセージに設定ページの作成とか関係ない実装も含まれてるよね。

commitは最初のうちはページ単位や機能単位で記録するようにしてみてください。
細かくなったらgitのrebase機能を使えばまとめることもできるので。

2021-10-05 03:06 UTC, mcz9mm requested changes
コメントしました！

2021-10-05 03:06 UTC, mcz9mm commented on lib/settings_page.dart
> +        preferredSize: Size.fromHeight(88),
しっかりデザイン通りになるようにしてください
88ptだとステータスバー周りの高さ込みになってしまっているので違和感があります。

<img width="350" alt="スクリーンショット 2021-10-05 11 29 51" src="https://user-images.githubusercontent.com/11751495/135950959-691ce0b2-ae82-484a-a479-db9a8cce0498.png">

<img width="930" alt="スクリーンショット 2021-10-05 11 30 08" src="https://user-images.githubusercontent.com/11751495/135950981-a99b426d-c08c-45dd-9437-032abfdf491e.png">

2021-10-05 03:06 UTC, mcz9mm commented on lib/settings_page.dart
> +        child: AppBar(
区切り線がないです
Dividerを使ってください
<img width="768" alt="スクリーンショット 2021-10-05 11 31 42" src="https://user-images.githubusercontent.com/11751495/135951089-d0aaca55-5db1-4df6-bf05-52b33a23a380.png">

2021-10-05 03:06 UTC, mcz9mm commented on lib/settings_page.dart
> +          Card(
アイコン箇所タップではなく、項目全体をタップ判定できるようにしてください
<img width="621" alt="スクリーンショット 2021-10-05 11 34 06" src="https://user-images.githubusercontent.com/11751495/135951307-bb31bb9a-5cb6-4b95-b6ab-507c1a330953.png">

2021-10-05 03:06 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +              child: Column(
レイアウトが崩れているので修正してください

・タイトルが見えない
・テキストに余白がない
・利用規約の上部分に余白がない

<img width="350" alt="スクリーンショット 2021-10-05 11 35 54" src="https://user-images.githubusercontent.com/11751495/135951477-91fc3ccc-9a36-4860-989a-5c55e4c8bd82.png">

2021-10-05 03:06 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +                  Container(
端末サイズによって高さが変わる部分は自動で端末サイズの高さを超えたらスクロールしてくれる
SingleChildScrollViewを使うと良いです

https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html

2021-10-05 03:06 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +                  Container(
SingleChildScrollViewを使うとここの部分の高さ設定が不要になります。

2021-10-05 03:06 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +  showModalBottomSheet<void>(
ここの処理ってプライバシーポリシーでも同様にshowModalBottomSheetを呼び出してるけど中身のコンテンツ以外は同じ処理だよね。なるべく共通なものは統一できるようにして使い回しが効くようにしてほしいです。

例えばshowModalBottomSheetを呼び出す関数だけ用意して、引数にcontextと表示するページを受け取れるようにWidgetを設定してあげれば、
```
void showModalPage(BuildContext context, Widget page) {
  showModalBottomSheet<void>(
    context: context,
    isScrollControlled: true,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(15)),
    ),
    builder: (context) => DraggableScrollableSheet(
      initialChildSize: 1.0,
      builder: (context, scrollController) => Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.vertical(top: Radius.circular(15)),
        ),
        child: page,
      ),
    ),
  );
}
```

こんな感じでページをStatelessWidgetとして分離できるはず。
```
class PrivacyPolicyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: [
          Text(
            'プライバシーポリシー',
            textAlign: TextAlign.center,
            style: TextStyle(
              fontSize: 17,
              fontWeight: FontWeight.bold,
            ),
          ),
          Divider(
            height: 0,
          ),
          Text(
            'プライバシーポリシー\n',
            style: TextStyle(fontSize: 14),
          ),
        ],
      ),
    );
  }
}

```

呼び出したい時にこの関数とページを設定してあげれば自由に好きなページを呼び出せる実装になります。
```
showModalPage(context, PrivacyPolicyPage());
```

2021-10-12 15:20 UTC, aoinishinaka commented on lib/settings_page.dart
> +        preferredSize: Size.fromHeight(88),
修正しました。

2021-10-12 22:55 UTC, mcz9mm commented on lib/settings_page.dart
> +          Card(
修正完了しましたか？

2021-10-12 22:55 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +              child: Column(
修正完了しましたか？

2021-10-12 22:55 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +                  Container(
修正しましたか？

2021-10-12 22:55 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +                  Container(
修正しましたか？

2021-10-12 22:55 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +  showModalBottomSheet<void>(
修正しましたか？

2021-10-12 23:00 UTC, mcz9mm reviewed
PRでコメントした箇所がどうなったのか返信してくれると助かります。
修正できたならその旨を各コメントに書くとか、わからずに詰まってるならその内容を返信するとかしてくれるとレビューしやすいです。

2021-10-12 23:00 UTC, mcz9mm commented on lib/settings_page.dart
> +        bottomOpacity: 0.0,
bottomを使うのでopacityを0にすると見えなくなります

2021-10-12 23:00 UTC, mcz9mm commented on lib/settings_page.dart
> +        bottomOpacity: 0.0,
色は分かりやすくしてます。
<img width="838" alt="スクリーンショット 2021-10-13 7 52 49" src="https://user-images.githubusercontent.com/11751495/137039806-362c0816-e896-4d5e-9147-e1bb9ae19e06.png">

2021-10-12 23:00 UTC, mcz9mm commented on lib/settings_page.dart
> +class MyDivider extends StatelessWidget {
Dividerのだけにクラスを用意するのはtoo muchかな。
カスタマイズ性があるならともかく使ってなさそうなので

2021-10-12 23:40 UTC, mcz9mm requested changes

2021-10-12 23:40 UTC, mcz9mm commented on lib/BottomSheet/showModelPage.dart
> +void showModalPage(BuildContext context, Widget page) {
`DraggableScrollableSheet `を使わなくてもいけるはず
```
  showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
    ),
    builder: (context) => page,
  );
```

2021-10-12 23:40 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +            height: 45,
これは45ptではないと思う
<img width="448" alt="スクリーンショット 2021-10-13 8 31 38" src="https://user-images.githubusercontent.com/11751495/137042608-1ea506bf-5881-4df9-bd00-3a9dab5a3e41.png">

2021-10-12 23:40 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +            padding: EdgeInsets.only(top: 18, bottom: 0),
`padding: EdgeInsets.only(top: 24, bottom: 11),`

2021-10-12 23:40 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +              color: Colors.grey[200],
`#F5F5F5`

2021-10-12 23:40 UTC, mcz9mm commented on lib/BottomSheet/term of service_page.dart
> +    return SingleChildScrollView(
スクロールさせたい箇所とそうでない箇所を上手く切り分けられるといいね。
ここまで書いたのでほぼ完成までいけると思います。
構造的にどうなってるか読んでみてほしいです。

https://user-images.githubusercontent.com/11751495/137042969-7174db78-4194-44d3-973d-5b17845f60b5.mp4

```  
@override
  Widget build(BuildContext context) {
    return Container(
      // 描画する高さが決まる
      height: MediaQuery.of(context).size.height * 0.9,
      child: Column(
        children: [
          Container(
            // "利用規約", "プラポリ"の部分
          ),
          Divider(
            height: 1,
          ),
          // タイトル部分はスクロールさせずに中身の部分だけスクロールさせる
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                children: [
                  Padding(
                    // ToDo: Figma通りの余白にすること
                    padding: const EdgeInsets.all(16.0),
                    child: Text(
                      'プライバシーポリシー\n'
                      style: TextStyle(fontSize: 14),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
```

2021-10-12 23:40 UTC, mcz9mm commented on lib/settings_page.dart
> +          Container(
高さの確保だけならSizedBox

2021-10-12 23:40 UTC, mcz9mm commented on lib/settings_page.dart
> +          Container(
SizedBox

2021-10-12 23:40 UTC, mcz9mm commented on lib/settings_page.dart
> +          Container(
SizedBox

2021-10-12 23:40 UTC, mcz9mm commented on lib/settings_page.dart
> +          Container(
SizedBox

2021-10-13 09:53 UTC, aoinishinaka commented on lib/BottomSheet/showModelPage.dart
> +void showModalPage(BuildContext context, Widget page) {
修正しました。

2021-10-13 09:53 UTC, aoinishinaka commented on lib/BottomSheet/term of service_page.dart
> +              color: Colors.grey[200],
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/BottomSheet/term of service_page.dart
> +            padding: EdgeInsets.only(top: 18, bottom: 0),
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/BottomSheet/term of service_page.dart
> +    return SingleChildScrollView(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/BottomSheet/term of service_page.dart
> +            height: 45,
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/settings_page.dart
> +        bottomOpacity: 0.0,
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/settings_page.dart
> +          Container(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/settings_page.dart
> +class MyDivider extends StatelessWidget {
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/BottomSheet/term of service_page.dart
> +  showModalBottomSheet<void>(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/BottomSheet/term of service_page.dart
> +              child: Column(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/BottomSheet/term of service_page.dart
> +                  Container(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/BottomSheet/term of service_page.dart
> +                  Container(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/settings_page.dart
> +          Container(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/settings_page.dart
> +          Container(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/settings_page.dart
> +          Container(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/settings_page.dart
> +        child: AppBar(
修正しました

2021-10-13 09:53 UTC, aoinishinaka commented on lib/settings_page.dart
> +          Card(
修正しました

2021-10-13 10:18 UTC, mcz9mm commented
OKです
よくがんばったね👍

2021-10-13 10:18 UTC, merged