Feature/tag page
shinonome-inc/mobile_Aoi_mogi_Qiita pull request #4
Opened 2021-10-16 02:31 UTC by aoinishinaka

TagDetailPageへの遷移以外のTagPageを実装しました。（TagDetailPageは押したTagを含む記事だけを表示する機能を実装すればよいのでしょうか？）

2021-10-18 09:38 UTC, mcz9mm commented
Figmaに記載してあるのでよく確認してね。
回答としてはYes。だけどAPIの取得を工夫しないといけないので注意してください。
(iOSも一緒なので他のモバイルコースの先輩に聞いてみたりしてね)

<img width="500" alt="スクリーンショット 2021-10-18 18 33 23" src="https://user-images.githubusercontent.com/11751495/137706160-610d9d76-672a-4147-a43e-955168c290b0.png">

> （TagDetailPageは押したTagを含む記事だけを表示する機能を実装すればよいのでしょうか？）

2021-10-18 09:51 UTC, mcz9mm requested changes
リクエストが403でUIの確認できないので一旦コメントしたところの修正お願いします。
別途確認できたらUI部分もチェックします

2021-10-18 09:51 UTC, mcz9mm commented on lib/Api/model/article.dart
> +    required this.created_at,
Flutterではキャメルケースで扱いたいので
`created_at `→`createdAt `で

2021-10-18 09:51 UTC, mcz9mm commented on lib/Api/model/article.dart
>        created_at: json['created_at'],
key名と変数が違くても対応できるよね
`createdAt: json['created_at'],`

2021-10-18 09:51 UTC, mcz9mm commented on lib/Api/model/taglist.dart
> +  final String icon_url;
ここも全部キャメルケースで
`iconUrl`
https://e-words.jp/w/%E3%82%AD%E3%83%A3%E3%83%A1%E3%83%AB%E3%82%B1%E3%83%BC%E3%82%B9.html

2021-10-18 09:51 UTC, mcz9mm commented on lib/Api/model/taglist.dart
> +  final int followers_count;
`followersCount `

2021-10-18 09:51 UTC, mcz9mm commented on lib/Api/model/taglist.dart
> +  final int items_count;
`itemsCount`

2021-10-18 09:51 UTC, mcz9mm commented on lib/Api/network_request.dart
> +      throw Exception('読み込めませんでした');
今じゃなくていいけど今後エラー画面作ろうね

<img width="300" alt="スクリーンショット 2021-10-18 18 44 59" src="https://user-images.githubusercontent.com/11751495/137707878-22cbfdfa-91a4-41a3-8283-02ff708519af.png">

2021-10-18 09:51 UTC, mcz9mm commented on lib/tag_page.dart
> +                            padding: const EdgeInsets.fromLTRB(0, 0, 0, 8),
下方向に余白を付けるだけならSizedBoxで良いんじゃないかな？

2021-10-21 04:57 UTC, mcz9mm reviewed
軽い修正ですが確認お願いします

2021-10-21 04:57 UTC, mcz9mm commented on lib/Api/model/taglist.dart
> +class TagList {
これってTagページで表示するデータの一つとしてのクラスを表現してるよね。
そうであればここは`List`じゃなくて単数の`Tag`で良いんじゃないかな？

2021-10-21 04:57 UTC, mcz9mm commented on lib/tag_page.dart
> +  final List<TagList> tagcard;
ここも`Tag`のListとして受け取るなら
`tagcard `ではなく`tagList`にしてみるのはどうかな？

2021-10-21 04:57 UTC, mcz9mm commented on lib/tag_page.dart
> +              final taglist = widget.tagcard[index];
`final taglist = widget.tagcard[index];`
listの中身のn番目を取得するならじゃない？
名称を変えるだけでわかりやすくなるはず
`final tag = widget.tagList[index];`

2021-10-21 04:57 UTC, mcz9mm commented on lib/tag_page.dart
> +                padding: EdgeInsets.all(8.0),
ここ16で

2021-10-23 14:46 UTC, aoinishinaka commented on lib/Api/model/taglist.dart
> +class TagList {
修正しました

2021-10-23 14:47 UTC, aoinishinaka commented on lib/Api/network_request.dart
> +      throw Exception('読み込めませんでした');
了解です

2021-10-23 14:49 UTC, aoinishinaka commented on lib/tag_page.dart
> +  final List<TagList> tagcard;
修正しました

2021-10-23 14:49 UTC, aoinishinaka commented on lib/tag_page.dart
> +                padding: EdgeInsets.all(8.0),
修正しました

2021-10-23 14:49 UTC, aoinishinaka commented on lib/tag_page.dart
> +                            padding: const EdgeInsets.fromLTRB(0, 0, 0, 8),
修正しました

2021-10-23 14:49 UTC, aoinishinaka commented on lib/Api/model/article.dart
> +    required this.created_at,
修正しました

2021-10-23 14:49 UTC, aoinishinaka commented on lib/Api/model/article.dart
>        created_at: json['created_at'],
修正しました

2021-10-23 14:49 UTC, aoinishinaka commented on lib/Api/model/taglist.dart
> +  final String icon_url;
修正しました

2021-10-23 14:49 UTC, aoinishinaka commented on lib/Api/model/taglist.dart
> +  final int followers_count;
修正しました

2021-10-23 14:49 UTC, aoinishinaka commented on lib/Api/model/taglist.dart
> +  final int items_count;
修正しました

2021-10-26 02:17 UTC, mcz9mm requested changes
1箇所修正できてないので確認お願いします

2021-10-26 02:17 UTC, mcz9mm commented on lib/tag_page.dart
> +  final List<Tag> tagcard;
tagcard→`tagList`

2021-10-28 02:43 UTC, mcz9mm approved these changes
コメント確認したら次の作業へ移りましょう。

2021-10-28 02:43 UTC, mcz9mm commented on lib/tag_page.dart
> +  final List<Tag> taglist;
キャメルケースを覚えよう。
単語同士を繋げるときのルールがあるのでチェックしておいてください。
Dartは基本的にキャメルケースを採用しているので今回だとtagとlistの繋げた名称なので`tagList`になります。

camelCase: キャメルケース
CamalCase: アッパーキャメルケース
snake_case: スネークケース
ebab-case: ケバブケース


別のブランチで修正してもらえればいいです

2021-10-28 02:44 UTC, merged